language: cpp
sudo: required
dist: xenial
compiler:
  - gcc
  - clang
os:
  - linux
services:
  - mysql
install:
  - sudo apt-get install libmysqlclient-dev odb libodb-dev libodb-mysql-dev -y
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/include/mysql
  - sudo ldconfig

before_script:
  - pwd
  - ls
  - sudo mysql -e 'CREATE DATABASE odb_test;'
  - mysql --user=travis --database=odb_test < person.sql
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..'
  - cmake ..
addons:
  apt:
    update: true

env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
script:
  # once CMake has done its job we just build using make as usual
  - make VERBOSE=1
  # if the project uses ctest we can run the tests like this
  # - make test
  - ./testodbaccess  --user root --password "" --database odb_test --host 127.0.0.1
